version: "0.2"
words:
  - abled
  - adafruit
  - addopts
  - armv
  - ATSAMD
  - autoattribute
  - autoclass
  - autofunction
  - automethod
  - automodule
  - autoproperty
  - baudrate
  - bgcolor
  - blinka
  - busdevice
  - busio
  - bysource
  - bytearray
  - capsys
  - CELLBORDER
  - CELLSPACING
  - CIRCUITPY
  - circuitpython
  - coef
  - datasheet
  - dhcplist
  - digitalio
  - Disabl
  - Dmitry
  - docstitle
  - Doherty
  - Eddystone
  - elif
  - Fals
  - fontcolor
  - fontname
  - fontsize
  - graphviz
  - Grinberg
  - hexlified
  - HHHBB
  - Hinch
  - intersphinx
  - isascii
  - Itsy
  - Kbps
  - labelloc
  - LENG
  - levelname
  - Mbps
  - microcontroller
  - microcontrollers
  - micropython
  - minversion
  - MOSI
  - multicasted
  - multicasting
  - multicasts
  - multiceiver
  - mypy
  - newrank
  - penwidth
  - Pinout
  - Pluss
  - pytest
  - ranksep
  - raspberrypi
  - repr
  - rgba
  - Rhys
  - Roboto
  - seealso
  - setlinewidth
  - setuptools
  - sparkfun
  - spidev
  - testpaths
  - toctree
  - twopi
  - urandom
  - venv
  - versionadded
  - versionchanged
  - viewcode
  - WLAN
  - xfer
