version: "0.2"
words:
  - abled
  - adafruit
  - addopts
  - armv
  - ATSAMD
  - baudrate
  - blinka
  - busdevice
  - busio
  - capsys
  - circuitpython
  - digitalio
  - Disabl
  - Dmitry
  - Doherty
  - Eddystone
  - elif
  - Fals
  - Grinberg
  - hexlified
  - HHHBB
  - Kbps
  - LENG
  - levelname
  - Mbps
  - micropython
  - minversion
  - MOSI
  - multicasted
  - multicasting
  - multicasts
  - mypy
  - pytest
  - raspberrypi
  - setuptools
  - spidev
  - testpaths
  - urandom
