version: "0.2"
words:
  - abled
  - adafruit
  - addopts
  - armv
  - ATSAMD
  - baudrate
  - blinka
  - busdevice
  - busio
  - capsys
  - CIRCUITPY
  - circuitpython
  - datasheet
  - digitalio
  - Disabl
  - Dmitry
  - Doherty
  - Eddystone
  - elif
  - Fals
  - Grinberg
  - hexlified
  - HHHBB
  - Hinch
  - Itsy
  - Kbps
  - LENG
  - levelname
  - Mbps
  - microcontroller
  - micropython
  - minversion
  - MOSI
  - multicasted
  - multicasting
  - multicasts
  - multiceiver
  - mypy
  - Pinout
  - pytest
  - raspberrypi
  - Rhys
  - seealso
  - setuptools
  - spidev
  - testpaths
  - toctree
  - urandom
  - venv
  - versionadded
  - xfer
