# SPDX-FileCopyrightText: 2020 Diego Elio Pettenò
#
# SPDX-License-Identifier: Unlicense

repos:
  - repo: https://github.com/python/black
    rev: 22.8.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/pylint
    rev: v2.15.3
    hooks:
      - id: pylint
        name: pylint (library code)
        types: [python]
        args:
          - --disable=consider-using-f-string,duplicate-code,too-many-public-methods,too-few-public-methods
        exclude: "^(docs/|examples/|tests/|setup.py$)"
        additional_dependencies: ["adafruit-circuitpython-minimqtt"]
      - id: pylint
        name: pylint (example code)
        description: Run pylint rules on "examples/*.py" files
        types: [python]
        files: "^examples/"
        args:
          - --disable=missing-docstring,invalid-name,consider-using-f-string,duplicate-code,import-error
      - id: pylint
        name: pylint (test code)
        description: Run pylint rules on "tests/*.py" files
        types: [python]
        additional_dependencies: [pytest]
        files: "^tests/"
        args:
          - --disable=import-error,invalid-name,protected-access,too-few-public-methods
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.981
    hooks:
      - id: mypy
        name: mypy (library code)
        exclude: "^(docs/|examples/|tests/|setup.py$)"
        types: [python]
