# SPDX-FileCopyrightText: 2021 Melissa LeBlanc-Williams for Adafruit Industries
#
# SPDX-License-Identifier: Unlicense

# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: latest
  apt_packages:
    - libgl1-mesa-dev
    - libxkbcommon-x11-0
    - graphviz
  jobs:
    pre_create_environment:
      - >-
        UV_INSTALL_DIR="${HOME}/.local/bin" &&
        curl -LsSf https://astral.sh/uv/install.sh | sh
      - ${HOME}/.local/bin/uv sync --group docs
    build:
      html:
        - >-
          ${HOME}/.local/bin/uv run
          sphinx-build docs docs/_build/html
    post_build:
      - mkdir -p ${READTHEDOCS_OUTPUT}/html/
      - mv docs/_build/html/* ${READTHEDOCS_OUTPUT}/html

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py
