name: Build CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions: {}

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v6
        id: python-setup
        with:
          python-version: "3.x"

      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Cache pre-commit environments
        uses: actions/cache@v4
        with:
          path: '~/.cache/pre-commit'
          key: pre-commit-${{ steps.python-setup.outputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install pre-commit and deps
        run: pip install pre-commit -r requirements.txt

      - name: Pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure

  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install testing tools
        run: pip install -r requirements.txt -r tests/requirements.txt

      - name: Collect coverage
        run: |
          coverage run -m pytest
          coverage report
          coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage.xml
          verbose: true # optional (default = false)

  build-docs:
    runs-on: ubuntu-latest
    env:
      QT_QPA_PLATFORM: offscreen
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Python 3.x
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install deps
        run: |-
          pip install -r docs/requirements.txt
          pip install -e .
          sudo apt-get update
          sudo apt-get install libgl1-mesa-dev libxkbcommon-x11-0 graphviz

      - name: Build docs
        working-directory: docs
        run: sphinx-build -E -W -b html . _build/html

      - name: Archive docs
        uses: actions/upload-artifact@v5
        with:
          name: docs
          path: ${{ github.workspace }}/docs/_build/html
