name: Build CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions: {}

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6
        id: python-setup
        with:
          python-version: "3.x"

      - uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
        with:
          python-version: ${{ steps.python-setup.outputs.python-version }}

      - name: Cache pre-commit environments
        uses: actions/cache@v4
        with:
          path: '~/.cache/pre-commit'
          key: pre-commit-${{ steps.python-setup.outputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files --show-diff-on-failure

  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6
        id: python-setup
        with:
          python-version: "3.x"

      - uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
        with:
          python-version: ${{ steps.python-setup.outputs.python-version }}

      - name: Install testing tools
        run: uv sync --group tests

      - name: Collect coverage
        env:
          UV_NO_SYNC: 1
        run: |
          uv run coverage run -m pytest
          uv run coverage report
          uv run coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage.xml
          verbose: true # optional (default = false)

  build-docs:
    runs-on: ubuntu-latest
    env:
      QT_QPA_PLATFORM: offscreen
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6
        id: python-setup
        with:
          python-version: "3.x"

      - uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
        with:
          python-version: ${{ steps.python-setup.outputs.python-version }}

      - name: Install deps
        run: |-
          uv sync --group docs
          sudo apt-get update
          sudo apt-get install libgl1-mesa-dev libxkbcommon-x11-0 graphviz

      - name: Build docs
        working-directory: docs
        env:
          UV_NO_SYNC: 1
        run: uv run sphinx-build -E -W -b html . _build/html

      - name: Archive docs
        uses: actions/upload-artifact@v5
        with:
          name: docs
          path: ${{ github.workspace }}/docs/_build/html
